### ISSUE TITLE
Use EnrichmentMap app to visualise enriched pathways from selected UMAP clusters of a single cell RNAseq dataset

### ISSUE THREAD

**Issue by jjacob12** [cytoscape/cytoscape-tutorials#79] opened 2023-01-15 21:54 UTC
Hello,
I previously generated a Seurat object which contains clusters of cancer cells growing amongst healthy cells. There were 3 clusters of cancer cells readily recognisable by their distinct gene expression profile. I used Seurat to identify differentially expressed genes in the 3 cancer clusters of interest using the FindMarkers() command. Around 2000-3000 genes were found per cluster with varying log fold change and significance. I'd like to use as input to Cytoscape EnrichmentMap this list of genes, with a view to GSEA or gProfiler and then visualisation. gProfiler reported 'error' with no details so I did not persevere with that tool. Instead I moved on to GSEA and I followed this tutorial (https://cytoscape.org/cytoscape-tutorials/protocols/enrichmentmap-pipeline/#/) but it is hard work as the lower parts of the text in many webpages are truncated. I used both a Chrome and Safari browser and got the same result.
 My question is: 
1) is it possible to use EnrichmentMap in the way I have described above (i.e. only a single list of ranked genes?)
2) the text truncations mean it is really difficult to follow the tutorials. Can this please be looked at as soon as possible? Zooming out does not work.
3) Is the below table the correct format for the .RNK file? (2 columns: gene column and avg_log_FC column)

Many thanks,
John

[dge.cl7.dyCbo.2.rnk.txt](https://github.com/cytoscape/cytoscape-tutorials/files/10421319/dge.cl7.dyCbo.2.rnk.txt)

**Comment by risserlin** [comment] 2023-01-16 15:25
Hi John, 
Sorry.  I didn't realize that some of those slides were cut off towards the bottom.  I will update it to fix that issue.  In the meantime there is a bookdown implementation of this tutorial that you can find here - https://baderlab.github.io/EnrichmentMap_Protocol/

Your rank file is in the right format but it only contains up-regulated genes so when looking at your enrichment results from GSEA it is important to only look at the positive results returned by GSEA as the negative results are from the lower part of your list which are not significant hits as opposed to down regulated genes.  

Any other feedback from g:profiler as it is often a very good tool for the list that you have created?  Maybe it was having some technical issues when you tried it.

**Comment by jjacob12** [comment] 2023-01-16 16:55
Hi Ruth,
The bookdown is exactly what I need - thanks for the link. I'm also curious why gProfiler did not work. There is no error message as such just the word "error".  I will send you my gene list that I pasted in to gProfiler. The list is made up of around 200 of the top upregulated genes from Seurat FindMarkers() and using the R package "fgsea", the full gene list  was enriched for specific GO, REACTOME, etc categories that made biological sense.

I really appreciate you getting back to me.

Best wishes 
John
Dr John Jacob

**Comment by risserlin** [comment] 2023-01-16 18:47
HI John, 
You can send me the list at ruth.isserlin at utoronto.ca so I can try and see what the issue is with gprofiler.  Were you using the gprofiler R package or the website directly?
I have been using fGSEA recently as well.  I have some scripts that will create enrichment maps directly from fGSEA results if you would like.   I should add it to the bookdown tutorial as well. 
Thanks, 
Ruth

**Comment by jjacob12** [comment] 2023-01-16 20:04
Hi Ruth,

Mysteriously, gProfier is now working. I guess you were right - there was a temporary glitch that has been ironed out. The results I’m getting are consistent with my earlier fgsea results, which is great, so I will carry on with the analysis in EnrichmentMap.
Regarding your scripts, it would be really great if you could send those. What R package would those scripts use?

Best wishes,
John

**Comment by jjacob12** [comment] 2023-01-16 20:12
Hi Ruth,

Just to add I was using the gProfiler website.

Thanks
John

**Comment by jjacob12** [comment] 2023-01-20 09:27
Hi Ruth,

Once a clustered network containing multiple nodes has been generated I can’t seem to ‘click and grab’ individual clusters with their nodes to reposition them so the graphic looks of publication quality. Using the tool selections at the base of the expression map network viewer only moves the cluster circles themselves but not the nodes within them or the annotations. I can’t find any documentation about this either, but then again it should be intuitive.

Best wishes,
John

**Comment by risserlin** [comment] 2023-01-20 14:18
Hi John, 
I am not sure at what point you are at.  It sound like your annotations are not moving with the cluster as they should be. 
 Does your network look something like this:
![Screen Shot 2023-01-20 at 9 13 45 AM](https://user-images.githubusercontent.com/3842763/213718379-ac6fc4d9-0d69-47c6-8dcb-f26c8016cb7b.png)

and you want it to look like this:
![Screen Shot 2023-01-20 at 9 16 02 AM](https://user-images.githubusercontent.com/3842763/213719466-88e9d536-eb13-472e-8ba7-4e69ddf43685.png)

When you select an entire cluster its annotation should move with it and if you move an individual node int the cluster the annotation should update itself based on the node's new position.  Is that the step you are on?

Ruth

**Comment by jjacob12** [comment] 2023-01-20 14:29
Hi Ruth,

The figure you sent is roughly the stage I was at when I sent the email, and you are right - the 2nd figure you sent shows what I would like the figure to eventually look like. Since I sent the email I have spent several hours manually moving each node and each cluster independently (I removed the individual annotations associated with a node). It does not seem possible to select a single cluster and the nodes there-in and move them as one, which is what I really need. I can select the text annotations and move those however.
Does that explain things?

Best wishes,
John

**Comment by jjacob12** [comment] 2023-01-20 14:45
Hi Ruth,
By moving text annotations I mean the cluster “title” not the individual node geneset names. Hope that makes sense.

Thanks,
John

**Comment by risserlin** [comment] 2023-01-20 14:55
HI John,
All of those parts should be moving together, the cluster, the individual nodes in the cluster and the title of the cluster.  It might be a bug.  In the past when I have encountered this issue I feel like I have saved my session, shut cytoscape and reopened cytoscpae and then restored my session to try and get the proper autoannotate behaviour back.
Which version of autoannotate are you working with?  (here is some useful documentation on it - https://autoannotate.readthedocs.io/en/latest/)  
I have created a question on the autoannotate github to see if there is an easier way of reassociating the nodes and annotations - https://github.com/BaderLab/AutoAnnotateApp/issues/185
Thanks, 
Ruth

**Comment by jjacob12** [comment] 2023-01-20 15:21
Hi Ruth,
I’m using the latest version of AutoAnnotate: 1.4.0. I have tried shutting down Cytoscape and re-opening but that doesn’t solve the problem. The mouse/trackpad (I have both) simply moves the whole network and it’s impossible to select a cluster. I have had a quick look through the AutoAnnotate link you sent but no mention of this issue. Moreover, I cannot uninstall AutoAnnotate from my Mac as the Uninstall button in App Manager is greyed out. I’m wondering whether I should uninstall Cytoscape and start afresh? Is there a way you know to do this on a Mac?
Best wishes,
John

**Comment by risserlin** [comment] 2023-01-20 15:32
Hi John, 
To make a group selection you have to hold command key and then click on the mouse and drag.  Does that action work for group selection?
Ruth

**Comment by jjacob12** [comment] 2023-01-20 15:44
Hi Ruth,
I tried that and it sort of works…I think. Will play around a bit more and come back to you.

Best wishes,
John

**Comment by mikekucera** [comment] 2023-01-20 16:05
There are a few ways to select a cluster in AutoAnnotate...

1) Click on the cluster name in the AutoAnnotate panel. This will select all the nodes in the cluster.
2) Right click on any node in a cluster, then in the context menu select "Apps > AutoAnnotate - Select Cluster"
3) Hold shift and draw a rectangle around the cluster. This can be kind of tricky if clusters are close together.

2 above is probably the easiest way.
When all the nodes in a cluster are selected you can grab any node and drag and it will drag the entire cluster with the annotations.

**Comment by jjacob12** [comment] 2023-01-20 16:20
HI Ruth and Mike,

Easy solutions after all. I can spend my time productively again. Thank you both!

John

**Closed as completed** 2023-01-22 11:08 UTC
Labels: question

**Comment by mikekucera** [comment] 2023-01-23 14:10
https://github.com/BaderLab/AutoAnnotateApp/issues/186

**Comment by jjacob12** [comment] 2023-01-27 08:56
Dear Mike,

Thanks, this is exactly what’s needed.

Best wishes,
John
